import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * ESLint for the whole workspace — `apps/api`, `apps/web` and
 * `packages/esquemas` from one root config, the same way `pnpm -r` runs one
 * `test` and one `typecheck`.
 *
 * Two things this config deliberately is NOT:
 *
 * 1. **Not a formatter.** No Prettier, no `eslint-config-prettier`, and not a
 *    single rule about quotes, semicolons, trailing commas, indentation or
 *    line width. Reformatting ~34k lines would bury every real finding under
 *    whitespace churn. `tsc` and this config check correctness; the diff of
 *    an actual change stays readable.
 *
 * 2. **Not a wall of warnings.** Every rule below is `error`, and `pnpm lint`
 *    runs with `--max-warnings 0`. A lint job that is allowed to be yellow
 *    teaches people that yellow is normal, and then it stops being read at
 *    all. If a rule cannot pass honestly today it is listed in DEFERRED
 *    below with its finding count and left OFF — never downgraded to `warn`,
 *    never silenced with a blanket `eslint-disable`, and never hidden behind
 *    an `ignores` entry that quietly drops real source.
 *
 * Conventions this codebase owns, which the config must not fight:
 *
 * - **Identifiers are Spanish** (`buscarContrato`, `PropiedadesEnvioDeFirma`,
 *   `nombreCompleto`) — see CLAUDE.md and DESIGN.md. No `naming-convention`
 *   rule is enabled, and none ever should be: every one of them assumes
 *   English. This also breaks `react-hooks/rules-of-hooks`; see DEFERRED.
 * - **Hexagonal/screaming architecture.** Exported `PropiedadesX`, `ComandoX`,
 *   `DatosX` and `FilaX` types are public surface on purpose, even when the
 *   only current consumer is their own file. Nothing here flags them.
 * - **NestJS decorators.** `experimentalDecorators`/`emitDecoratorMetadata`
 *   come from each package's own tsconfig, which the type-aware setup below
 *   reads directly — so decorator and parameter-injection semantics are the
 *   ones `tsc` uses, not a re-declared approximation.
 * - **Vitest, not Jest.** Specs are `*.spec.ts`/`*.spec.tsx` colocated with
 *   their source, plus `*.testing.ts` for shared fixtures and test doubles.
 *   They are linted like the source beside them, with exactly one documented
 *   exception: the `no-unsafe-*` family, which the test harnesses themselves
 *   make unenforceable — see the TEST FILES section at the bottom.
 */
export default tseslint.config(
  {
    // Build output and machine-local state only. Every directory that holds
    // hand-written source is linted — `apps/api/generated/` is the Prisma
    // client (git-ignored, regenerated by `prisma generate`, and absent
    // entirely until it runs), and `.claude/` is per-machine Claude Code
    // state whose `worktrees/` holds throwaway checkouts of this same repo.
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "apps/api/generated/**",
      "apps/web/dev-dist/**",
      ".claude/**",
      "var/**",
    ],
  },

  // ── This file itself ──────────────────────────────────────────────────
  // Plain ESM, not covered by any tsconfig, so it gets the core rules only
  // and never enters the type-aware pass below.
  {
    files: ["**/*.mjs"],
    extends: [js.configs.recommended],
    languageOptions: { globals: globals.nodeBuiltin },
  },

  // ── TypeScript, type-aware ────────────────────────────────────────────
  {
    files: ["**/*.ts", "**/*.tsx"],
    extends: [js.configs.recommended, tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        // `projectService` follows each file to its own package's tsconfig,
        // so `apps/web` is linted with `jsx`/DOM and `apps/api` with its
        // decorator flags — no second, drifting copy of those settings here.
        projectService: {
          // The four TS files no tsconfig `include` covers. They are real
          // source and are linted; they just fall back to default compiler
          // options because no project claims them.
          allowDefaultProject: [
            "apps/api/prisma.config.ts",
            "apps/api/vitest.config.ts",
            "apps/api/vitest.integration.config.ts",
            "packages/esquemas/vitest.config.ts",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The `_` prefix is this repo's existing, consistent marker for a
      // binding that exists only to be discarded — `const { poe: _omitido,
      // ...resto }`, `evaluate<T>(_funcion: ...)`. Teaching the rule that
      // convention is what makes it usable: 11 of the rule's 14 findings on
      // 4dcfa45 were deliberate discards, and a rule that is wrong 11 times
      // out of 14 gets switched off by the first person it annoys. The
      // other 3 were genuinely dead imports, and this PR deletes them.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],

      // ── Extra rules from `strictTypeChecked` ──────────────────────────
      // Each of these is a correctness or dead-code check (none of them
      // touch formatting) and each already reports zero findings across the
      // workspace, so they cost nothing today and catch the next mistake.
      "@typescript-eslint/no-dynamic-delete": "error",
      "@typescript-eslint/no-meaningless-void-operator": "error",
      "@typescript-eslint/no-mixed-enums": "error",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
      "@typescript-eslint/no-unnecessary-template-expression": "error",
      "@typescript-eslint/no-unnecessary-type-arguments": "error",
      "@typescript-eslint/no-unnecessary-type-conversion": "error",
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/prefer-literal-enum-member": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/prefer-return-this-type": "error",
      "@typescript-eslint/related-getter-setter-pairs": "error",
      // `error-handling-correctness-only` is the mode `strictTypeChecked`
      // itself picks, and the only one that belongs here: it flags an
      // `await` whose placement changes which `try` a rejection lands in,
      // and stays silent about `return await` as a matter of taste. The
      // default mode (`in-try-catch`) is the taste one — 40 findings, zero
      // of them bugs.
      "@typescript-eslint/return-await": ["error", "error-handling-correctness-only"],
      "@typescript-eslint/unified-signatures": "error",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",

      // The `no-unsafe-*` family stays ON here, as `recommendedTypeChecked`
      // ships it, and is scoped off for test files only — see TEST FILES at
      // the bottom of this config for the measurement and the reasoning.
      // This is the rule set that stops an `any` from entering production
      // source at all, which is the whole point of a codebase with zero
      // `any` and zero `@ts-ignore` in it.

      // `no-floating-promises`, `no-misused-promises`,
      // `no-unnecessary-type-assertion` and `no-redundant-type-constituents`
      // were all deferred here and are now enforced at their
      // `recommendedTypeChecked` default: their findings were fixed at the
      // source rather than configured away. Nothing below re-lists them —
      // an explicit `"error"` for a rule the preset already errors on is a
      // second copy that can silently drift.

      // ── DEFERRED ──────────────────────────────────────────────────────
      // Enabled by `recommendedTypeChecked`, switched off here because each
      // one reports findings this codebase would have to make *worse* to
      // silence. Counts are re-measured on fa62fef by force-enabling each
      // rule over the whole workspace; the split is production source vs.
      // `*.spec.ts(x)`/`*.testing.ts`.
      //
      // 50 findings — 49 in test files, 1 in production source. Every one is
      // an `async` method with nothing to await because a port declares
      // `Promise<T>`: the in-memory doubles (`HasherFalso.hashear`,
      // `EmisorFalso.emitir`, `PaginaFalsa.pdf`) implement async interfaces
      // whose real adapters do I/O, and the production one
      // (`AuthController.yo`) is a NestJS route handler. Dropping `async`
      // does not even compile — the body would have to return
      // `Promise.resolve(...)` by hand — so the rule's advice here is
      // strictly worse code. No true positives.
      "@typescript-eslint/require-await": "off",
      // 25, all in specs, and all four shapes are deliberate:
      //   17 — `Controlador.prototype.manejar` handed to a fake
      //        `ExecutionContext` in the guard specs. NestJS's own
      //        `context.getHandler()` returns exactly that unbound prototype
      //        method; the guard reads decorator metadata off it and never
      //        calls it, so binding would misrepresent what is under test.
      //    4 — static factories (`Dni.crear`, `DireccionMac.crear`) gathered
      //        into a table-driven spec. They never touch `this`.
      //    3 — `expect(controlador.cerrar).toHaveBeenCalledTimes(1)`, the
      //        idiomatic Vitest spy assertion.
      //    1 — saving `globalThis.crypto.randomUUID` to restore it after a
      //        stub. Binding a saved global would defeat the restore.
      // No true positives.
      "@typescript-eslint/unbound-method": "off",
      // 3, all the same shape: a plain `number` compared against a NestJS
      // `HttpStatus` member (`configuracionHttp.ts:88` twice,
      // `respuestaDeError.ts:189`). Express and Nest both type a status code
      // as `number` — `HttpException.getStatus()` returns `number`, and an
      // express error's `.status` is whatever the body parser put there — so
      // the enum is only ever on one side. The two ways to silence it are
      // both worse: annotating the local `HttpStatus` would be a lie
      // (`configuracionHttp` defaults it to `0`, which is not a member) and
      // rests on TypeScript's `number`-into-numeric-enum hole, and comparing
      // bare `413`/`400` literals instead throws away the names that make
      // the branch readable. This repo declares no `enum` of its own, so the
      // rule's entire surface here is those three comparisons.
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
    },
  },

  // ── Per-package environments ──────────────────────────────────────────
  {
    files: ["apps/api/**/*.ts"],
    languageOptions: { globals: globals.node },
  },
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
  },
  // `packages/esquemas` gets neither on purpose: its tsconfig sets
  // `"types": []` and a DOM-free `lib` so the package stays importable from
  // the browser. Declaring Node globals here would undo that guarantee at
  // the lint layer.

  // ── React hooks (apps/web) ────────────────────────────────────────────
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    extends: [reactHooks.configs.flat["recommended-latest"]],
    rules: {
      // `react-hooks/exhaustive-deps` was deferred here over one real
      // finding — `VisorDeDocumento.tsx:55`, a missing `onCambiaEstado` —
      // which its own PR has since fixed. It now reports zero across
      // `apps/web`, so it is left at the plugin's `recommended-latest`
      // default and the next missing dependency is caught while it is still
      // cheap. It is not re-listed below for the same reason the type-aware
      // block does not re-list its graduates.

      // ── DEFERRED ──────────────────────────────────────────────────────
      // `rules-of-hooks` hardcodes `/^use[A-Z0-9]/` as the definition of a
      // custom hook, with no configuration hook of any kind (see
      // `isHookName` in the plugin's dist). This project's hooks are named
      // in Spanish — `usarSesionActual`, `usarBusquedaDeContratos`,
      // `usarValorDebounced` — so the rule sees ordinary functions calling
      // `useState`, and reports 14 errors that are all false positives. It
      // has no true positives here. Renaming the hooks to satisfy a linter
      // would be the tail wagging the dog, so the rule stays off until
      // either the plugin gains a name pattern or the team decides
      // otherwise.
      "react-hooks/rules-of-hooks": "off",
      // 1 each — `Toast.tsx:26` writes a ref during render;
      // `PasoFirmaDual.tsx:119` sets state synchronously inside an effect.
      // Both are real React Compiler findings and both change behaviour to
      // fix.
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },

  // ── TEST FILES ────────────────────────────────────────────────────────
  // The one per-rule relaxation in this config, and the only place a rule is
  // scoped rather than deferred outright.
  //
  // Measured on 6bf9980, the family reported 96 findings across the
  // workspace: 94 in test files and 2 in production source. That split is
  // not a coincidence — the 94 are two test harnesses whose public types are
  // `any` by design, and the 2 production ones are fixed in this same change
  // (`LimiteEstricto.ts`, now reading `Reflect.getMetadata` into `unknown`).
  //
  // - **`supertest`** (92 of the 94). `request(app).get(...)` resolves to a
  //   `Response` whose `body` is typed `any`, because supertest cannot know
  //   what any given endpoint returns. Every assertion against a response
  //   body in the `apps/api` controller specs therefore trips the family:
  //   `respuesta.body.error` is `no-unsafe-member-access`, `const cuerpo =
  //   respuesta.body` is `no-unsafe-assignment`, and handing either to
  //   `expect()` is `no-unsafe-argument`.
  // - **Vitest asymmetric matchers** (the other 2, in
  //   `FormularioBorrador.spec.tsx`). `expect.objectContaining(...)` is
  //   declared as returning `any` so it can stand in for any expected value.
  //
  // Neither is fixable in this repo's source: both come from a dependency's
  // published type declarations, and the only local "fixes" are a cast or an
  // `eslint-disable` — the exact hole the family exists to catch, moved
  // somewhere less visible. Keeping the family off everywhere to accommodate
  // them would give up production enforcement for nothing.
  //
  // So the family is enforced in production source, where an `any` is a
  // genuine defect, and off in test files, where it is the harness talking.
  // A spec asserting against an untyped response body is doing its job; the
  // assertion is the type check.
  //
  // `no-unsafe-return` is in the list despite having zero findings today.
  // Leaving it on for specs would flag only one thing — a spec helper that
  // wraps a supertest call and returns its body — while the copy-pasted
  // inline version of the same access goes unflagged, because the other four
  // rules are off here. That penalises the better-factored spec, so the
  // family is scoped as a unit.
  {
    files: ["**/*.spec.ts", "**/*.spec.tsx", "**/*.testing.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  // On, now that `exhaustive-deps` is — the two only make sense together.
  // While that rule was off, all 7 of the `eslint-disable-next-line
  // react-hooks/exhaustive-deps` comments in `apps/web` were trivially
  // "unused", so this reported nothing but the deferral it was already
  // documenting. With the rule enforcing again, 6 of the 7 are suppressing a
  // real finding and the 7th was suppressing nothing at all — measured by
  // deleting it and confirming `exhaustive-deps` still reports zero at that
  // effect. Its explanation was worth keeping and stayed as a plain comment;
  // only the directive went. That is the whole value of this option: a
  // suppression that has stopped suppressing anything reads as a live
  // exception and is not one.
  { linterOptions: { reportUnusedDisableDirectives: "error" } },
);
